// Generated by `pnpm --filter @docengine/writing corpus:docs` — do not edit.
// Every corpus file, imported so the build bundles it (the production image ships the bundle only).
import manifest from './manifest.json' with { type: 'json' };
import e0 from './examples/borderline/character.json' with { type: 'json' };
import e1 from './examples/borderline/context.json' with { type: 'json' };
import e2 from './examples/borderline/dialogue_adjacent.json' with { type: 'json' };
import e3 from './examples/borderline/economics.json' with { type: 'json' };
import e4 from './examples/borderline/ending.json' with { type: 'json' };
import e5 from './examples/borderline/explanation.json' with { type: 'json' };
import e6 from './examples/borderline/hook.json' with { type: 'json' };
import e7 from './examples/borderline/numbers.json' with { type: 'json' };
import e8 from './examples/borderline/other.json' with { type: 'json' };
import e9 from './examples/borderline/payoff.json' with { type: 'json' };
import e10 from './examples/borderline/scene.json' with { type: 'json' };
import e11 from './examples/borderline/transition.json' with { type: 'json' };
import e12 from './examples/borderline/uncertainty.json' with { type: 'json' };
import e13 from './examples/house_style/house-voice.json' with { type: 'json' };
import e14 from './examples/negative/character.json' with { type: 'json' };
import e15 from './examples/negative/context.json' with { type: 'json' };
import e16 from './examples/negative/dialogue_adjacent.json' with { type: 'json' };
import e17 from './examples/negative/economics.json' with { type: 'json' };
import e18 from './examples/negative/ending.json' with { type: 'json' };
import e19 from './examples/negative/explanation.json' with { type: 'json' };
import e20 from './examples/negative/hook.json' with { type: 'json' };
import e21 from './examples/negative/numbers.json' with { type: 'json' };
import e22 from './examples/negative/other.json' with { type: 'json' };
import e23 from './examples/negative/payoff.json' with { type: 'json' };
import e24 from './examples/negative/scene.json' with { type: 'json' };
import e25 from './examples/negative/transition.json' with { type: 'json' };
import e26 from './examples/negative/uncertainty.json' with { type: 'json' };
import e27 from './examples/positive/character.json' with { type: 'json' };
import e28 from './examples/positive/context.json' with { type: 'json' };
import e29 from './examples/positive/dialogue_adjacent.json' with { type: 'json' };
import e30 from './examples/positive/economics.json' with { type: 'json' };
import e31 from './examples/positive/ending.json' with { type: 'json' };
import e32 from './examples/positive/explanation.json' with { type: 'json' };
import e33 from './examples/positive/hook.json' with { type: 'json' };
import e34 from './examples/positive/numbers.json' with { type: 'json' };
import e35 from './examples/positive/other.json' with { type: 'json' };
import e36 from './examples/positive/payoff.json' with { type: 'json' };
import e37 from './examples/positive/scene.json' with { type: 'json' };
import e38 from './examples/positive/transition.json' with { type: 'json' };
import e39 from './examples/positive/uncertainty.json' with { type: 'json' };

export const MANIFEST: unknown = manifest;
export const CORPUS_FILES: { path: string; examples: unknown }[] = [
  { path: 'borderline/character.json', examples: e0 },
  { path: 'borderline/context.json', examples: e1 },
  { path: 'borderline/dialogue_adjacent.json', examples: e2 },
  { path: 'borderline/economics.json', examples: e3 },
  { path: 'borderline/ending.json', examples: e4 },
  { path: 'borderline/explanation.json', examples: e5 },
  { path: 'borderline/hook.json', examples: e6 },
  { path: 'borderline/numbers.json', examples: e7 },
  { path: 'borderline/other.json', examples: e8 },
  { path: 'borderline/payoff.json', examples: e9 },
  { path: 'borderline/scene.json', examples: e10 },
  { path: 'borderline/transition.json', examples: e11 },
  { path: 'borderline/uncertainty.json', examples: e12 },
  { path: 'house_style/house-voice.json', examples: e13 },
  { path: 'negative/character.json', examples: e14 },
  { path: 'negative/context.json', examples: e15 },
  { path: 'negative/dialogue_adjacent.json', examples: e16 },
  { path: 'negative/economics.json', examples: e17 },
  { path: 'negative/ending.json', examples: e18 },
  { path: 'negative/explanation.json', examples: e19 },
  { path: 'negative/hook.json', examples: e20 },
  { path: 'negative/numbers.json', examples: e21 },
  { path: 'negative/other.json', examples: e22 },
  { path: 'negative/payoff.json', examples: e23 },
  { path: 'negative/scene.json', examples: e24 },
  { path: 'negative/transition.json', examples: e25 },
  { path: 'negative/uncertainty.json', examples: e26 },
  { path: 'positive/character.json', examples: e27 },
  { path: 'positive/context.json', examples: e28 },
  { path: 'positive/dialogue_adjacent.json', examples: e29 },
  { path: 'positive/economics.json', examples: e30 },
  { path: 'positive/ending.json', examples: e31 },
  { path: 'positive/explanation.json', examples: e32 },
  { path: 'positive/hook.json', examples: e33 },
  { path: 'positive/numbers.json', examples: e34 },
  { path: 'positive/other.json', examples: e35 },
  { path: 'positive/payoff.json', examples: e36 },
  { path: 'positive/scene.json', examples: e37 },
  { path: 'positive/transition.json', examples: e38 },
  { path: 'positive/uncertainty.json', examples: e39 },
];
