import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { styleBibleMarkdown } from './bible.ts';
import { patternsMarkdown, rubricMarkdown } from './docs.ts';

/**
 * Writes the generated corpus documents and the corpus import index:
 *   pnpm --filter @docengine/writing corpus:docs
 * Run it after editing bible.ts, rubric.ts, the pattern notes, or adding or
 * removing a corpus file.
 */

const corpus = join(dirname(fileURLToPath(import.meta.url)), '..', 'corpus');

export function corpusFiles(): string[] {
  const root = join(corpus, 'examples');
  return readdirSync(root)
    .filter((d) => statSync(join(root, d)).isDirectory())
    .sort()
    .flatMap((d) => readdirSync(join(root, d)).filter((f) => f.endsWith('.json')).sort().map((f) => `${d}/${f}`));
}

export function corpusIndex(files: readonly string[]): string {
  return [
    '// Generated by `pnpm --filter @docengine/writing corpus:docs` — do not edit.',
    '// Every corpus file, imported so the build bundles it (the production image ships the bundle only).',
    "import manifest from './manifest.json' with { type: 'json' };",
    ...files.map((f, i) => `import e${i} from './examples/${f}' with { type: 'json' };`),
    '',
    'export const MANIFEST: unknown = manifest;',
    'export const CORPUS_FILES: { path: string; examples: unknown }[] = [',
    ...files.map((f, i) => `  { path: '${f}', examples: e${i} },`),
    '];',
    '',
  ].join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(join(corpus, 'STYLE_BIBLE.md'), styleBibleMarkdown());
  writeFileSync(join(corpus, 'RUBRIC.md'), rubricMarkdown());
  writeFileSync(join(corpus, 'annotations', 'PATTERNS.md'), patternsMarkdown());
  const files = corpusFiles();
  writeFileSync(join(corpus, 'index.ts'), corpusIndex(files));
  console.log(`Wrote STYLE_BIBLE.md, RUBRIC.md, annotations/PATTERNS.md and index.ts (${files.length} corpus files)`);
}
